### ISSUE TITLE
libgee deprecation

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#16]
Are there any reason why you deprecate libgee?

Have you considered performance issues?

**Comment by grindhold** [comment]
There are two main reasons. 
The first reason can be read in #12 . I want the library to be as introspectable as possible.
The second reason is to avoid dependencies where not really neccessary.

Are there known performance issues with GLib's List-implementation?

**Comment by esodan** [comment]
You're right about introspection issues, see bug https://bugzilla.gnome.org/show_bug.cgi?id=639908

I think we need to check if removing Gee is a solution, because your API doesn't provide any Gee public API today, but in the future. Then just providing functions to make easy to use by bindings creates some burning on maintain, but keeps code easy to maintain because Gee is heavily tied to interfaces and makes easy to implement new ones, like lists could be any implementation not just Gee ones, that's I do with GXml, where it relays on libxml using C structures to handle lists of nodes and GXml uses Gee to provide them an iterator to be used in foreach and other goodness from Gee's collections.

Then, yes, try to keep Gee internally as possible is good idea for bindings.

Yes, if we implement public API using Gee interfaces, should make unusable from bidings directly if no helped functions are included, the problem here is generics, that is a powerful feature of Vala, making easy to implement powerful interfaces to mostly any case.

Yes, we can add helper functions to avoid generics to bindings.

Yes, implement Vala's generics interfaces from C are heavy if no Vala is used, because in C generics requires more parameters, but not impossible.

GList are good for short number of members, but a pain when we should walk through to get the nth number in large collections, compared with Gee because it is an array but can behaves like a List.

About dependencies, yes, you have dropped a dependency that is not strictly necessary and relays just on GLib, that should be good for GFlow.

May be I don't provide you with enough reasons to get Gee back and I should take in account on design of new interfaces for GFlow proposal.

**Comment by grindhold** [comment]
For the performance issues:

I think inside a Node, a GLib.List suffices to keep track of the Docks. Let's face it: A node that contains so many Docks that it would cause a feelable breakdown of performance when iterating through them would not be very usable from a UI-aspect.
For the NodeView however, this could be otherwise, as we can't predict how many Nodes a user wants to manage inside a NodeView. Those numbers could get huge.

**Comment by grindhold** [comment]
i've given it some more thoughts. i come to the conclusion that it doesn't matter if we use a linked list or an array list because:
  * When we need to iterate over every element that is in the list, we have to traverse the whole list anyway.
  * Graph-connections between nodes are expressed through references  to nodes that reside inside docks. So this has nothing to do with the list.
But we could run some tests on this, e.g. create a nodeview with a ridiculously huge amount of nodes and see how it behaves.

**Comment by esodan** [comment]
Then maybe its not time to discus this.

Consider that may any one would like to get an input/output from a given name or number, in this cases is better to use a HasTable and an Array. Any way we can add this as methods, then no collections will be exposed, to find any item in internal collection's implementations, using Gee or the actual one.

For my proposals to use interfaces, I could create one from the actual classes and then in the future add API for new requirements.

**Comment by grindhold** [comment]
I'll close this discussion. Let's build some tests for speed and see if and when perfomance reaches critical levels.
