### ISSUE TITLE
gflow: connecting sink to source causes stackoverflow

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#38]
<s>when trying to connect a source to a sink everything runs fine
when trying to connect a sink to a source, the connect methods will call each other repeatedly causing a stackoverflow

```Vala
using GFlow;
int main(string[] argv) {
var x = new SimpleSink(0);
var y = new SimpleSource(0);
x.link_to(y);
}
```
</s>

special circumstances appear to be neccessary to trigger this  bug. i will investigate.

**Comment by esodan** [comment]
When create Unit Tests, I found a rise  problem when try to connect in both
directions, that makes me think to change source as connection less, then
just sinks will hear value changes from sources.

May you want to do so and add tests cases to ensure this problem is gone.

**Comment by grindhold** [comment]
making sources connectionless is not an option. people would not be able to traverse the flow graph with their applications (or at least only in one direction - from sink to source - which can be very cumbersome). that's a crucial feature.

**Comment by esodan** [comment]
Let me understand what you're talking about.

What traverse means for GtkFlow, "traverse"?

Why in just one direction is a problem?

Why if the possibility to do it mutters, no the way is done, but do it in
both directions?

If is it a performance problem because iteration in large collections to
get a Source from a Sink, why hash tables aren't an option, or any other?

**Comment by grindhold** [comment]
Because a simple pointer (or in Vala-terms reference) does exactly what we need. There is no need for additional data structures. We have an implementation problem, not a design problem. The bug has been already fixed for most cases, as i cannot trigger it with the simple program i posted in the OP of this issue. Apparently i discovered some edge case that involves using the library in a 2-layer-application through gobject-introspection which introduces non-obvious reasons why this could happen. And those reasons must be investigated.

With traversal, i mean following the connections from one node to another over their connections. 

Why this is a problem? In some cases you might want to start your traversal at the beginning. This is completely depending on your use-case for the library. If I encountered a library that would offer only one way for no obvious reasons (except for "the programmers were to lazy to solve their problems"). Imagine, you encountered this library in the wild and looked at the API, and you found this out, you'd be like "huh? why can i directly get a source from a sink but not the other way round?", too, wouldn't you?

The datastructure of Nodes Sinks and Sources cover everything we need without any additional datastructures.

I will debug into that edge case and see what went wrong and how to avoid it.
This is a trivial bug, not a non-trivial design-issue.

**Comment by grindhold** [comment]
fixed as of d08c77f

As i said, it was a trivial bug, fixed by moving and reindenting one single line. Not a full blown design issue.

**Comment by grindhold** [comment]
maybe i should point it out this way:

GFlow generally does two things for the programmer who uses it:

1. Maintain the datastructure of a non-cyclic directed graph and provide means for the user to navigate this graph. 
For example, II have two nodes A and B. A and B are connected through A's first source and B's first sink. Then i can get from A to B via:

```Vala
b = a.sources[0].sink.node;
```

2. Keeping track of the values and their transportation/updating/doing recalculations inside the flow graph, so that the values are always up to date and are ready for the user to read them at any time.

I often get the impression that your propositions try to enhance the second part but forget about the first. The first feature is not simply a by-product of the flow graph, it's crucial to analyze the structure of a given graph that has been entered by the user and the programmer outside the lib has no idea of.

**Comment by esodan** [comment]
I really love to talk about issues. Remember you are the owner of your
project, I just try to help as far as I can with the time left me.

My opinions just reflects my poor knowledge about GtkFlow needs.

I really what to have a graphical independent GFlow library, providing not
just GtkFlow required features, but a general analysis tool.

I mean, I see GFlow as:

a) A way to abstract complex processes

b) Provide interfaces to be implemented by any process to communicate with
others getting or providing data or a stream

C) Abstraction should make a programmer to connect compatible sources to
sinks to get a result from complex processes calculations/processing

**Comment by grindhold** [comment]
speaking in mathematical terms, the graph is directed when viewed in the context of signal processing, because the data only flows in one direction. an edge in this graph means "data flows from this source to that sink"
When viewed as a structure of connections, this connection is not directed anymore, or it can be viewed as symmetrical relation. imagine two directed edges between every source and sink (one being "this source provides that sink with data" and the other one being "this sink draws data from that source") or one undirected edge ("these two docks are connected").

this is not exclusively relevant in the context of gtkflow. it's true that  users can enter gflow-graphs through gtkflow, but one could also load a graph-structure for gflow from a textual representation in a file or from somewhere else and never display it through gtkflow. an example for this would be someone building a neural network with gflow.

**Comment by esodan** [comment]
When I say connectionless I mean "no data flow".

Could source be a connectionless class providing different methods of data
pass through and small enough to be efficient?

Could Sink be a connection oriented to get data from sources and be small
to efficient implementation?

Could Node be a manager of it sources and sinks, in a way it the navigation
provider to go to/from sinks, sources and other Nodes?

Most of these al already there. But why don't move navigation from Dock to
Node? Could these simplify source and Sink implementations while provides
the features for graph?

**Comment by grindhold** [comment]
Seeing Node and SimpleNode as managers is not really cool on the level of GFlow because of two reasons:

1. It would mean introducing methods like Node.get_nth_source(int) or Node.get_nth_sink(int). which i think is unneccessary because we already got everything as properties with permissions set so everyone can access them.
2. Introducing wrappers to this node is up to the programmer who inherits from SimpleNode or implements Node. Only at application level a programmer can tell what the sources and sinks contained by a node stand for. So on his application level he can say (in the example of a logical AND node) that the sink of this node is an operation result. and that the other sink is the inverted result of the operation, thereby implementing methods like MyNode.get_result() -> Sink or MyNode.get_inverted_result() -> Sink on top of his implementation.
We do not have that kind of information at the abstract level of GFlow

**Comment by esodan** [comment]
I would like to see your opinions about other questions I made before.

What if I want to implement a Source and want to leave Sink, or any other,
worry connected sinks. Having a reference to an object, may be in other
process or hearing on DBus may could limit implementations, don't you think?

I think Node is the perfect place to manage and access connected Sinks to
sources.

Could a Source or Sink live without a Node?

Seeing Node and SimpleNode as managers is not really cool on the level of
GFlow because of two reasons:

   1. It would mean introducing methods like Node.get_nth_source(int) or
   Node.get_nth_sink(int). which i think is unneccessary because we already
   got everything as properties with permissions set so everyone can access
   them.
   2. Introducing wrappers to this node is up to the programmer who
   inherits from SimpleNode or implements Node. Only at application level a
   programmer can tell what the sources and sinks contained by a node stand
   for. So on his application level he can say (in the example of a logical
   AND node) that the sink of this node is an operation result. and that the
   other sink is the inverted result of the operation, thereby implementing
   methods like MyNode.get_result() -> Sink or MyNode.get_inverted_result() ->
   Sink on top of his implementation. We do not have that kind of information
   at the abstract level of GFlow

—
Reply to this email directly or view it on GitHub
<https://github.com/grindhold/libgtkflow/issues/38#issuecomment-131814243>.

**Comment by grindhold** [comment]
Docks can, in theory live without Docks. In this case they can't be displayed to the user via GtkFlow, but yes, you can use them without nodes.
