### ISSUE TITLE
Keep sink docks and source docks on the same line

### ISSUE THREAD

**Issue by benwaffle** [grindhold/libgtkflow#56]

**Comment by grindhold** [comment]
in 4d5d37a i added a minimum meson version to be checked.
if you encounter any lower meson-versions that are able to
build the project correctly, feel free to adjust the value
in ```meson.build```

**Comment by grindhold** [comment]
we can now render sinks and sources on the same line by using a newly
introduced NodeRenderer called DocklineNodeRenderer instead of the
DefaultNodeRenderer.

As a side effect, i made the API of existing NodeRenderer classes public,
so you can directly inherit from them. You are not bound to implementing
the interface NodeRenderer all by yourself anymore if you only want to
change little things

**Comment by grindhold** [comment]
enjoy, @benwaffle  :)
